-- ==========================================================
-- Historic data import for Eli's Artisan Bakery
-- Generated by scripts/import-historic-data.js
-- Generated at: 2026-03-17T11:22:56.307Z
-- ==========================================================

BEGIN;

-- Temp tables for ID mapping
CREATE TEMP TABLE _week_map (label TEXT PRIMARY KEY, id UUID NOT NULL);
CREATE TEMP TABLE _product_map (week_label TEXT NOT NULL, product_name TEXT NOT NULL, id UUID NOT NULL, PRIMARY KEY (week_label, product_name));
CREATE TEMP TABLE _customer_map (name TEXT PRIMARY KEY, id UUID NOT NULL);
CREATE TEMP TABLE _order_map (week_label TEXT NOT NULL, customer_name TEXT NOT NULL, id UUID NOT NULL, PRIMARY KEY (week_label, customer_name));

-- ============================================================
-- WEEKS
-- ============================================================
INSERT INTO _week_map (label, id)
SELECT 'Week of 9 January 2026', id FROM (
  INSERT INTO week (label, status, collection_days, opens_at, closes_at)
  VALUES (
    'Week of 9 January 2026',
    'closed',
    '{friday}',
    '2026-01-05T08:00:00+08:00'::timestamptz,
    '2026-01-08T18:00:00+08:00'::timestamptz
  )
  RETURNING id
) AS ins;

INSERT INTO _week_map (label, id)
SELECT 'Week of 16 January 2026', id FROM (
  INSERT INTO week (label, status, collection_days, opens_at, closes_at)
  VALUES (
    'Week of 16 January 2026',
    'closed',
    '{friday}',
    '2026-01-12T08:00:00+08:00'::timestamptz,
    '2026-01-15T18:00:00+08:00'::timestamptz
  )
  RETURNING id
) AS ins;

INSERT INTO _week_map (label, id)
SELECT 'Week of 23 January 2026', id FROM (
  INSERT INTO week (label, status, collection_days, opens_at, closes_at)
  VALUES (
    'Week of 23 January 2026',
    'closed',
    '{friday}',
    '2026-01-19T08:00:00+08:00'::timestamptz,
    '2026-01-22T18:00:00+08:00'::timestamptz
  )
  RETURNING id
) AS ins;

INSERT INTO _week_map (label, id)
SELECT 'Week of 30 January 2026', id FROM (
  INSERT INTO week (label, status, collection_days, opens_at, closes_at)
  VALUES (
    'Week of 30 January 2026',
    'closed',
    '{saturday}',
    '2026-01-26T08:00:00+08:00'::timestamptz,
    '2026-01-29T18:00:00+08:00'::timestamptz
  )
  RETURNING id
) AS ins;

INSERT INTO _week_map (label, id)
SELECT 'Week of 6 February 2026', id FROM (
  INSERT INTO week (label, status, collection_days, opens_at, closes_at)
  VALUES (
    'Week of 6 February 2026',
    'closed',
    '{friday}',
    '2026-02-02T08:00:00+08:00'::timestamptz,
    '2026-02-05T18:00:00+08:00'::timestamptz
  )
  RETURNING id
) AS ins;

INSERT INTO _week_map (label, id)
SELECT 'Week of 13 February 2026', id FROM (
  INSERT INTO week (label, status, collection_days, opens_at, closes_at)
  VALUES (
    'Week of 13 February 2026',
    'closed',
    '{friday}',
    '2026-02-09T08:00:00+08:00'::timestamptz,
    '2026-02-12T18:00:00+08:00'::timestamptz
  )
  RETURNING id
) AS ins;

INSERT INTO _week_map (label, id)
SELECT 'Week of 20 March 2026', id FROM (
  INSERT INTO week (label, status, collection_days, opens_at, closes_at)
  VALUES (
    'Week of 20 March 2026',
    'closed',
    '{friday}',
    '2026-03-16T08:00:00+08:00'::timestamptz,
    '2026-03-19T18:00:00+08:00'::timestamptz
  )
  RETURNING id
) AS ins;

-- ============================================================
-- PRODUCTS
-- ============================================================
INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 9 January 2026', 'Sourdough', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    'Sourdough',
    11.00,
    'each',
    0
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 9 January 2026', 'Focaccia', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    'Focaccia',
    14.00,
    'each',
    1
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 9 January 2026', 'Pizza Dough', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    'Pizza Dough',
    4.00,
    'each',
    2
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 9 January 2026', 'Burger Buns', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    'Burger Buns',
    2.20,
    'each',
    3
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 9 January 2026', 'Tarte au Citron', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    'Tarte au Citron',
    60.00,
    'each',
    4
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 16 January 2026', 'Focaccia - Regular (toms + Garlic)', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 16 January 2026'),
    'Focaccia - Regular (toms + Garlic)',
    14.00,
    'each',
    0
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 16 January 2026', 'Pizza Dough', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 16 January 2026'),
    'Pizza Dough',
    4.00,
    'each',
    1
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 16 January 2026', 'Burger Buns', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 16 January 2026'),
    'Burger Buns',
    2.20,
    'each',
    2
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 16 January 2026', 'Fougasse', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 16 January 2026'),
    'Fougasse',
    6.00,
    'each',
    3
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 16 January 2026', 'Banana Choc Muffins', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 16 January 2026'),
    'Banana Choc Muffins',
    3.50,
    'each',
    4
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 23 January 2026', 'Sourdough', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 23 January 2026'),
    'Sourdough',
    11.00,
    'each',
    0
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 23 January 2026', 'Focaccia - Regular (toms + Garlic)', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 23 January 2026'),
    'Focaccia - Regular (toms + Garlic)',
    14.00,
    'each',
    1
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 23 January 2026', 'Pizza Dough', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 23 January 2026'),
    'Pizza Dough',
    4.00,
    'each',
    2
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 23 January 2026', 'Burger Buns', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 23 January 2026'),
    'Burger Buns',
    2.20,
    'each',
    3
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 23 January 2026', 'Fougasse', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 23 January 2026'),
    'Fougasse',
    6.00,
    'each',
    4
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 30 January 2026', 'Sourdough', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 30 January 2026'),
    'Sourdough',
    11.00,
    'each',
    0
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 30 January 2026', 'Focaccia Regular', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 30 January 2026'),
    'Focaccia Regular',
    14.00,
    'each',
    1
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 30 January 2026', 'Focaccia Sun Toms + Olives', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 30 January 2026'),
    'Focaccia Sun Toms + Olives',
    16.00,
    'each',
    2
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 30 January 2026', 'Pizza Dough', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 30 January 2026'),
    'Pizza Dough',
    4.00,
    'each',
    3
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 30 January 2026', 'Fougasse', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 30 January 2026'),
    'Fougasse',
    6.00,
    'each',
    4
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 30 January 2026', 'Burger Buns', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 30 January 2026'),
    'Burger Buns',
    2.20,
    'each',
    5
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 30 January 2026', 'Banana Choc Muffins', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 30 January 2026'),
    'Banana Choc Muffins',
    3.50,
    'each',
    6
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 30 January 2026', 'Mince Pies', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 30 January 2026'),
    'Mince Pies',
    3.50,
    'each',
    7
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 30 January 2026', 'Tarte au Citron', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 30 January 2026'),
    'Tarte au Citron',
    60.00,
    'each',
    8
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 6 February 2026', 'Sourdough', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 6 February 2026'),
    'Sourdough',
    11.00,
    'each',
    0
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 6 February 2026', 'Focaccia - Regular (toms, Garlic, Rose)', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 6 February 2026'),
    'Focaccia - Regular (toms, Garlic, Rose)',
    14.00,
    'each',
    1
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 6 February 2026', 'Pizza Dough', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 6 February 2026'),
    'Pizza Dough',
    4.00,
    'each',
    2
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 6 February 2026', 'Burger Buns', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 6 February 2026'),
    'Burger Buns',
    2.20,
    'each',
    3
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 6 February 2026', 'Butter Bean Dip', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 6 February 2026'),
    'Butter Bean Dip',
    10.00,
    'each',
    4
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 13 February 2026', 'Focaccia - Regular (toms, Garlic, Rose)', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 13 February 2026'),
    'Focaccia - Regular (toms, Garlic, Rose)',
    14.00,
    'each',
    0
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 13 February 2026', 'Pizza Dough', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 13 February 2026'),
    'Pizza Dough',
    4.00,
    'each',
    1
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 13 February 2026', 'Burger Buns', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 13 February 2026'),
    'Burger Buns',
    2.20,
    'each',
    2
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 13 February 2026', 'Fougasse', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 13 February 2026'),
    'Fougasse',
    6.00,
    'each',
    3
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 20 March 2026', 'Sourdough', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    'Sourdough',
    11.00,
    'each',
    0
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 20 March 2026', 'Pizza Dough', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    'Pizza Dough',
    4.00,
    'each',
    1
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 20 March 2026', 'Burger Buns', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    'Burger Buns',
    2.20,
    'each',
    2
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 20 March 2026', 'Fougasse', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    'Fougasse',
    6.00,
    'each',
    3
  )
  RETURNING id
) AS ins;

INSERT INTO _product_map (week_label, product_name, id)
SELECT 'Week of 20 March 2026', 'Hot X Buns', id FROM (
  INSERT INTO product (week_id, name, price, unit_label, display_order)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    'Hot X Buns',
    10.00,
    'pack of 6',
    4
  )
  RETURNING id
) AS ins;

-- ============================================================
-- CUSTOMERS
-- ============================================================
INSERT INTO _customer_map (name, id)
SELECT 'Geraldine Taylor', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Geraldine Taylor', 'historic_000', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Mandy Noel', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Mandy Noel', 'historic_001', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Georgie', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Georgie', 'historic_002', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Varun', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Varun', 'historic_003', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Kate', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Kate', 'historic_004', true)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Susan Prakasam', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Susan Prakasam', 'historic_005', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Olya', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Olya', 'historic_006', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Karolina', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Karolina', 'historic_007', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Gracie', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Gracie', 'historic_008', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Minnie', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Minnie', 'historic_009', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Ayesha Durante', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Ayesha Durante', 'historic_010', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Alex Derham', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Alex Derham', 'historic_011', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Lisa', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Lisa', 'historic_012', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'AA Sg', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('AA Sg', 'historic_013', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Sandra', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Sandra', 'historic_014', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

-- "Susan" from week 23 Jan is the same as "Susan Prakasam"
INSERT INTO _customer_map (name, id)
SELECT 'Susan', id FROM _customer_map WHERE name = 'Susan Prakasam';

INSERT INTO _customer_map (name, id)
SELECT 'Sammy Loder', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Sammy Loder', 'historic_016', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Shruti Thakar', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Shruti Thakar', 'historic_017', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Jill Pitcher', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Jill Pitcher', 'historic_018', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Purna', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Purna', 'historic_019', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Teresa', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Teresa', 'historic_020', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Oiying', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Oiying', 'historic_021', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Marian Janmaat', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Marian Janmaat', 'historic_022', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Neha', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Neha', 'historic_023', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Olivia Nicaise', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Olivia Nicaise', 'historic_024', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Michelle', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Michelle', 'historic_025', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

INSERT INTO _customer_map (name, id)
SELECT 'Sherry', id FROM (
  INSERT INTO customer (name, whatsapp_number, is_on_account)
  VALUES ('Sherry', 'historic_026', false)
  ON CONFLICT (whatsapp_number) DO NOTHING
  RETURNING id
) AS ins;

-- "Sammy" from week 20 Mar is the same as "Sammy Loder"
INSERT INTO _customer_map (name, id)
SELECT 'Sammy', id FROM _customer_map WHERE name = 'Sammy Loder';

-- ============================================================
-- ORDERS
-- ============================================================
INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 9 January 2026', 'Geraldine Taylor', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Geraldine Taylor'),
    'friday',
    'paid',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 9 January 2026', 'Mandy Noel', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Mandy Noel'),
    'friday',
    'paid',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 9 January 2026', 'Georgie', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Georgie'),
    'friday',
    'pending',
    'check with Wendy'
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 9 January 2026', 'Varun', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Varun'),
    'friday',
    'paid',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 9 January 2026', 'Kate', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Kate'),
    'friday',
    'on_account',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 9 January 2026', 'Susan Prakasam', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Susan Prakasam'),
    'friday',
    'paid',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 9 January 2026', 'Olya', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Olya'),
    'friday',
    'paid',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 9 January 2026', 'Karolina', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Karolina'),
    'friday',
    'paid',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 9 January 2026', 'Gracie', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 9 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Gracie'),
    'friday',
    'paid',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 16 January 2026', 'Minnie', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 16 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Minnie'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 16 January 2026', 'Ayesha Durante', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 16 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Ayesha Durante'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 16 January 2026', 'Georgie', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 16 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Georgie'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 16 January 2026', 'Alex Derham', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 16 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Alex Derham'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 16 January 2026', 'Lisa', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 16 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Lisa'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 23 January 2026', 'Mandy Noel', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 23 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Mandy Noel'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 23 January 2026', 'Georgie', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 23 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Georgie'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 23 January 2026', 'AA Sg', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 23 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'AA Sg'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 23 January 2026', 'Sandra', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 23 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Sandra'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 23 January 2026', 'Susan', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 23 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Susan'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 30 January 2026', 'Olya', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 30 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Olya'),
    'saturday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 30 January 2026', 'Georgie', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 30 January 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Georgie'),
    'saturday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 6 February 2026', 'Sammy Loder', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 6 February 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Sammy Loder'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 6 February 2026', 'Georgie', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 6 February 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Georgie'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 6 February 2026', 'Geraldine Taylor', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 6 February 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Geraldine Taylor'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 6 February 2026', 'Shruti Thakar', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 6 February 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Shruti Thakar'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 6 February 2026', 'Jill Pitcher', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 6 February 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Jill Pitcher'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 13 February 2026', 'Georgie', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 13 February 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Georgie'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 13 February 2026', 'Purna', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 13 February 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Purna'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 13 February 2026', 'Teresa', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 13 February 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Teresa'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Gracie', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Gracie'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Oiying', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Oiying'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Georgie', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Georgie'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Marian Janmaat', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Marian Janmaat'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Neha', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Neha'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Purna', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Purna'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Alex Derham', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Alex Derham'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Susan Prakasam', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Susan Prakasam'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Olivia Nicaise', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Olivia Nicaise'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Michelle', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Michelle'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Teresa', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Teresa'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Sherry', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Sherry'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

INSERT INTO _order_map (week_label, customer_name, id)
SELECT 'Week of 20 March 2026', 'Sammy', id FROM (
  INSERT INTO "order" (week_id, customer_id, collection_day, payment_status, notes)
  VALUES (
    (SELECT id FROM _week_map WHERE label = 'Week of 20 March 2026'),
    (SELECT id FROM _customer_map WHERE name = 'Sammy'),
    'friday',
    'pending',
    NULL
  )
  RETURNING id
) AS ins;

-- ============================================================
-- ORDER ITEMS
-- ============================================================
INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Geraldine Taylor'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Burger Buns'),
  10
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Geraldine Taylor'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Tarte au Citron'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Mandy Noel'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Focaccia'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Mandy Noel'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Burger Buns'),
  6
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Mandy Noel'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Tarte au Citron'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Georgie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Pizza Dough'),
  3
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Varun'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Sourdough'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Varun'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Pizza Dough'),
  4
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Kate'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Sourdough'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Kate'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Pizza Dough'),
  6
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Susan Prakasam'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Pizza Dough'),
  2
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Susan Prakasam'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Burger Buns'),
  6
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Olya'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Focaccia'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Olya'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Pizza Dough'),
  2
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Olya'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Burger Buns'),
  2
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Karolina'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Sourdough'),
  2
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Gracie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Pizza Dough'),
  2
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 9 January 2026' AND customer_name = 'Gracie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 9 January 2026' AND product_name = 'Burger Buns'),
  3
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 16 January 2026' AND customer_name = 'Minnie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 16 January 2026' AND product_name = 'Pizza Dough'),
  6
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 16 January 2026' AND customer_name = 'Ayesha Durante'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 16 January 2026' AND product_name = 'Focaccia - Regular (toms + Garlic)'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 16 January 2026' AND customer_name = 'Georgie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 16 January 2026' AND product_name = 'Pizza Dough'),
  3
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 16 January 2026' AND customer_name = 'Georgie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 16 January 2026' AND product_name = 'Fougasse'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 16 January 2026' AND customer_name = 'Alex Derham'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 16 January 2026' AND product_name = 'Pizza Dough'),
  5
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 16 January 2026' AND customer_name = 'Lisa'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 16 January 2026' AND product_name = 'Burger Buns'),
  6
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 16 January 2026' AND customer_name = 'Lisa'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 16 January 2026' AND product_name = 'Banana Choc Muffins'),
  8
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 23 January 2026' AND customer_name = 'Mandy Noel'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 23 January 2026' AND product_name = 'Burger Buns'),
  8
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 23 January 2026' AND customer_name = 'Georgie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 23 January 2026' AND product_name = 'Pizza Dough'),
  5
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 23 January 2026' AND customer_name = 'Georgie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 23 January 2026' AND product_name = 'Fougasse'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 23 January 2026' AND customer_name = 'AA Sg'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 23 January 2026' AND product_name = 'Sourdough'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 23 January 2026' AND customer_name = 'AA Sg'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 23 January 2026' AND product_name = 'Fougasse'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 23 January 2026' AND customer_name = 'Sandra'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 23 January 2026' AND product_name = 'Sourdough'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 23 January 2026' AND customer_name = 'Susan'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 23 January 2026' AND product_name = 'Pizza Dough'),
  4
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 23 January 2026' AND customer_name = 'Susan'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 23 January 2026' AND product_name = 'Burger Buns'),
  8
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 30 January 2026' AND customer_name = 'Olya'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 30 January 2026' AND product_name = 'Fougasse'),
  2
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 30 January 2026' AND customer_name = 'Olya'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 30 January 2026' AND product_name = 'Burger Buns'),
  6
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 30 January 2026' AND customer_name = 'Georgie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 30 January 2026' AND product_name = 'Pizza Dough'),
  4
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 6 February 2026' AND customer_name = 'Sammy Loder'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 6 February 2026' AND product_name = 'Sourdough'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 6 February 2026' AND customer_name = 'Sammy Loder'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 6 February 2026' AND product_name = 'Pizza Dough'),
  4
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 6 February 2026' AND customer_name = 'Sammy Loder'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 6 February 2026' AND product_name = 'Butter Bean Dip'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 6 February 2026' AND customer_name = 'Georgie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 6 February 2026' AND product_name = 'Pizza Dough'),
  4
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 6 February 2026' AND customer_name = 'Geraldine Taylor'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 6 February 2026' AND product_name = 'Pizza Dough'),
  4
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 6 February 2026' AND customer_name = 'Geraldine Taylor'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 6 February 2026' AND product_name = 'Burger Buns'),
  10
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 6 February 2026' AND customer_name = 'Shruti Thakar'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 6 February 2026' AND product_name = 'Focaccia - Regular (toms, Garlic, Rose)'),
  2
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 6 February 2026' AND customer_name = 'Jill Pitcher'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 6 February 2026' AND product_name = 'Sourdough'),
  2
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 13 February 2026' AND customer_name = 'Georgie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 13 February 2026' AND product_name = 'Pizza Dough'),
  6
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 13 February 2026' AND customer_name = 'Georgie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 13 February 2026' AND product_name = 'Fougasse'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 13 February 2026' AND customer_name = 'Purna'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 13 February 2026' AND product_name = 'Pizza Dough'),
  4
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 13 February 2026' AND customer_name = 'Purna'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 13 February 2026' AND product_name = 'Fougasse'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 13 February 2026' AND customer_name = 'Teresa'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 13 February 2026' AND product_name = 'Fougasse'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Gracie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Pizza Dough'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Gracie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Hot X Buns'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Oiying'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Hot X Buns'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Georgie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Pizza Dough'),
  6
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Georgie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Fougasse'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Georgie'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Hot X Buns'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Marian Janmaat'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Burger Buns'),
  10
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Marian Janmaat'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Hot X Buns'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Neha'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Pizza Dough'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Neha'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Hot X Buns'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Purna'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Hot X Buns'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Alex Derham'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Hot X Buns'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Susan Prakasam'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Hot X Buns'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Olivia Nicaise'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Hot X Buns'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Michelle'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Sourdough'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Teresa'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Sourdough'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Teresa'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Hot X Buns'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Sherry'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Pizza Dough'),
  12
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Sherry'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Hot X Buns'),
  1
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Sammy'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Pizza Dough'),
  4
);

INSERT INTO order_item (order_id, product_id, quantity)
VALUES (
  (SELECT id FROM _order_map WHERE week_label = 'Week of 20 March 2026' AND customer_name = 'Sammy'),
  (SELECT id FROM _product_map WHERE week_label = 'Week of 20 March 2026' AND product_name = 'Hot X Buns'),
  1
);

-- ============================================================
-- CLEANUP
-- ============================================================
DROP TABLE _order_map;
DROP TABLE _customer_map;
DROP TABLE _product_map;
DROP TABLE _week_map;

COMMIT;
